"""
Layer 2: turns Layer-1 invoice JSON (the nested dicts produced by
generic_parser.build_invoices — see orchestrator.run_two_sheet_joined)
into flat, Tally-importable "Accounting Voucher" rows, in the same column
shape as AccountingVouchers_B2B.xlsx / AccountingVouchers_B2C_Updated.xlsx.

SCOPE (current): Sales only. Purchase will reuse this same module once
the direction (Dr/Cr swap, Input vs Output tax ledgers, "Local Purchase"
naming) is confirmed — see the note at the bottom of the file.

DESIGN DECISIONS — read this before changing ledger names or amounts
------------------------------------------------------------------
1. B2B vs B2C is decided purely by PARTYGSTIN presence on the invoice
   (see split_b2b_b2c). This *is* check #1 from the brief ("GST number
   absent in B2C"): it's not a separate validation step, it's the
   classification rule itself. Every invoice ends up in exactly one
   bucket; nothing is silently dropped.

2. GST-rate ledger lines are DATA-DRIVEN off invoice["tax_breakup"], not a
   fixed template. Both sample files always emit the same 7/8 ledger rows
   per voucher (incl. explicit ₹0 rows for 18% on a 5%-only invoice) —
   that's an artifact of this particular business only ever selling at
   5%/18%, not a general Tally requirement. Since parse_summary() already
   drops zero-taxable buckets before they reach the JSON (see
   generic_parser.parse_summary), we only ever see the rates that actually
   occurred on that invoice, and that's what we emit — no ₹0 filler rows.
   If you specifically need the fixed-7/8-row shape to match a downstream
   tool, tell me and I'll add a "pad to known rate set" option.

3. Interstate vs intrastate is read directly off which tax fields are
   populated in tax_breakup (IGSTAMOUNT>0 => interstate; CGSTAMOUNT/
   SGSTAMOUNT>0 => intrastate) — NOT recomputed from STATECODE. Layer 1
   already reconciled these amounts against BILLAMOUNT, so they're the
   source of truth. STATECODE is only used to fill the
   "Buyer/Supplier - State" / "Place of Supply" columns, plus a soft
   consistency check (flagged in the report, not a hard failure).

4. SGST vs UTGST naming for the intrastate case is controlled by
   config.home_state_is_ut (default True, matching the Chandigarh
   samples). Flip it if your registered state is a regular State, not a
   Union Territory.

5. Ledger name spelling matches the sample files' ledger masters EXACTLY
   for the rates/cases actually observed (5% and 18%, intrastate only —
   including the double space in "Local Sales  GST 5%", which is real,
   not a typo). Rates and cases not in either sample — 12%, 28%,
   interstate/IGST, and SGST for a non-UT home state — are generated by
   extending that same convention, just swapping in the percentage value
   (confirmed as correct by the user, not a guess):
     Local Sales GST {rate}%      (single space — the 5% double-space is
                                    the one confirmed exception)
     Interstate Sales GST {rate}%
     Output CGST {rate/2}%
     Output SGST {rate/2}%   (non-UT home state)
     Output UTGST {rate/2}%  (UT home state)
     Output IGST {rate}%

6. Every voucher gets a "Round Off" ledger line when |ROUNDOFFAMOUNT| is
   non-trivial, sized so Dr total == Cr total exactly (check #3). Sign
   convention: ROUNDOFFAMOUNT < 0 (bill rounded down) => Dr "Round Off";
   ROUNDOFFAMOUNT > 0 (rounded up) => Cr "Round Off". This is the
   standard Tally convention.

7. Only invoices with is_validated == True are exported. Everything else
   (is_validated False or None — no matched items, or Layer 1's own
   reconciliation failed) is skipped and reported separately, never
   silently included.
"""
from dataclasses import dataclass, field
import pandas as pd

# ---------------------------------------------------------------------------
# Ledger naming
# ---------------------------------------------------------------------------

# Exact spelling confirmed against AccountingVouchers_B2B.xlsx /
# AccountingVouchers_B2C_Updated.xlsx ledger masters.
SALES_LEDGER_OVERRIDES = {
    5: "Local Sales  GST 5%",   # double space — confirmed from sample, not a typo here
    18: "Local Sales GST 18%",
}
ZERO_RATE_SALES_LEDGER = "Local Sales 0%"  # confirmed from B2C sample

# Rates/cases not present in either sample file (12%, 28%, interstate/IGST,
# SGST for a non-UT home state) are generated by extending the confirmed
# 5%/18% convention with the percentage swapped in — confirmed correct by
# the user. Nothing currently in this list; kept as a hook in case a future
# case (e.g. a cess ledger name) needs the same "confirm before relying on
# this" treatment.
LEDGER_NAME_ASSUMPTIONS = []


def fmt_rate(x: float) -> str:
    """5 -> '5', 2.5 -> '2.5', 9.0 -> '9'."""
    if float(x) == int(x):
        return str(int(x))
    return str(round(x, 2)).rstrip("0").rstrip(".")


def sales_ledger_name(rate: float, interstate: bool) -> str:
    if rate == 0:
        return ZERO_RATE_SALES_LEDGER
    if interstate:
        return f"Interstate Sales GST {fmt_rate(rate)}%"
    return SALES_LEDGER_OVERRIDES.get(rate, f"Local Sales GST {fmt_rate(rate)}%")


def tax_ledger_name(component: str, rate: float) -> str:
    """component: 'CGST' | 'SGST' | 'UTGST' | 'IGST'."""
    if component == "IGST":
        return f"Output IGST {fmt_rate(rate)}%"
    half = rate / 2
    return f"Output {component} {fmt_rate(half)}%"


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

@dataclass
class TallyExportConfig:
    home_state_is_ut: bool = True          # True -> UTGST naming, False -> SGST naming, for intrastate sales
    country: str = "India"
    round_off_ledger_name: str = "Round Off"
    balance_tolerance: float = 0.02        # rupees; Dr/Cr mismatches beyond this are flagged
    require_gstin_for_b2b: bool = True      # sanity check, not a hard filter


# ---------------------------------------------------------------------------
# Output column layout — matches the sample files exactly
# ---------------------------------------------------------------------------

COMMON_COLUMNS = [
    "Voucher Date", "Voucher Type Name", "Voucher Number",
    "Buyer/Supplier - Address", "Buyer/Supplier - Pincode",
    "Ledger Name", "Ledger Amount", "Ledger Amount Dr/Cr",
    "Item Name", "Billed Quantity", "Item Rate", "Item Rate per", "Item Amount",
    "Change Mode ", "Buyer/Supplier - Bill to/from",
]
B2B_IDENTITY_COLUMN = "Buyer/Supplier - GSTIN/UIN"
B2C_IDENTITY_COLUMN = "Buyer/Supplier - GST Registration Type"
TRAILING_COLUMNS = ["Buyer/Supplier - Country", "Buyer/Supplier - State", "Buyer/Supplier - Place of Supply"]

B2B_COLUMNS = COMMON_COLUMNS + [B2B_IDENTITY_COLUMN] + TRAILING_COLUMNS
B2C_COLUMNS = COMMON_COLUMNS + [B2C_IDENTITY_COLUMN] + TRAILING_COLUMNS


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def split_state(statecode):
    """'04-Chandigarh' -> ('04', 'Chandigarh'). Falls back gracefully if the
    field is missing or doesn't contain the expected '-' separator."""
    if not statecode:
        return None, None
    s = str(statecode)
    if "-" in s:
        code, name = s.split("-", 1)
        return code.strip(), name.strip()
    return None, s.strip()


def split_b2b_b2c(invoices: list) -> tuple:
    """The classification IS the GST-number-absent check: PARTYGSTIN
    present -> B2B, absent/blank -> B2C. Nothing else decides this."""
    b2b, b2c = [], []
    for inv in invoices:
        gstin = inv.get("PARTYGSTIN")
        if gstin and str(gstin).strip():
            b2b.append(inv)
        else:
            b2c.append(inv)
    return b2b, b2c


@dataclass
class TallyExportReport:
    voucher_type: str = ""
    mode: str = ""
    total_invoices_in: int = 0
    skipped_not_validated: list = field(default_factory=list)   # VOUCHERNUMBERs
    skipped_no_tax_breakup: list = field(default_factory=list)  # VOUCHERNUMBERs
    balance_mismatches: list = field(default_factory=list)      # dicts
    gstin_state_mismatches: list = field(default_factory=list)  # dicts: intrastate/interstate vs STATECODE inconsistency
    vouchers_written: int = 0
    rows_written: int = 0


# ---------------------------------------------------------------------------
# Core: one invoice -> its ledger rows
# ---------------------------------------------------------------------------

def _base_row(invoice, mode, config: TallyExportConfig) -> dict:
    _, state_name = split_state(invoice.get("STATECODE"))
    row = {
        "Voucher Date": invoice.get("DATE"),
        "Voucher Type Name": invoice.get("VOUCHERTYPE"),
        "Voucher Number": invoice.get("VOUCHERNUMBER"),
        "Buyer/Supplier - Address": None,   # not present in Layer-1 JSON; both samples' Address
                                             # column is itself corrupted data (holds unrelated
                                             # voucher numbers), so left blank rather than replicated
        "Buyer/Supplier - Pincode": None,
        "Ledger Name": None,
        "Ledger Amount": None,
        "Ledger Amount Dr/Cr": None,
        "Item Name": None, "Billed Quantity": None, "Item Rate": None,
        "Item Rate per": None, "Item Amount": None,
        "Change Mode ": "Accounting Invoice",
        "Buyer/Supplier - Bill to/from": invoice.get("PARTYNAME"),
        "Buyer/Supplier - Country": config.country,
        "Buyer/Supplier - State": state_name,
        "Buyer/Supplier - Place of Supply": state_name,
    }
    if mode == "B2B":
        row[B2B_IDENTITY_COLUMN] = invoice.get("PARTYGSTIN")
    else:
        row[B2C_IDENTITY_COLUMN] = "Unregistered/Consumer"
    return row


def build_voucher_rows(invoice: dict, mode: str, config: TallyExportConfig, report: TallyExportReport):
    """Returns a list of row dicts for one invoice, or [] if it's skipped
    (reasons recorded on `report`). Also appends any balance/consistency
    findings to `report`."""
    voucher_no = invoice.get("VOUCHERNUMBER")

    if invoice.get("is_validated") is not True:
        report.skipped_not_validated.append(voucher_no)
        return []

    tax_breakup = invoice.get("tax_breakup") or []
    if not tax_breakup:
        report.skipped_no_tax_breakup.append(voucher_no)
        return []

    base = _base_row(invoice, mode, config)
    rows = []

    bill_amount = float(invoice.get("BILLAMOUNT") or 0.0)
    party_name = invoice.get("PARTYNAME")

    # 1. Dr: party ledger, full bill amount (this is fixed — it's what was
    # actually billed/collected; everything else balances against it)
    dr_row = dict(base)
    dr_row["Ledger Name"] = party_name
    dr_row["Ledger Amount"] = round(bill_amount, 2)
    dr_row["Ledger Amount Dr/Cr"] = "Dr"
    rows.append(dr_row)

    total_cr = 0.0

    # 2. Cr: sales + tax ledgers, one group per rate bucket actually present
    for bucket in tax_breakup:
        rate = bucket.get("GSTRATE", 0)
        taxable = float(bucket.get("TAXABLEVALUE") or 0.0)
        cgst = float(bucket.get("CGSTAMOUNT") or 0.0)
        sgst = float(bucket.get("SGSTAMOUNT") or 0.0)
        igst = float(bucket.get("IGSTAMOUNT") or 0.0)
        cess = float(bucket.get("CESSAMOUNT") or 0.0)

        interstate = igst > 0

        # soft consistency check: IGST and CGST/SGST populated on the same
        # bucket should never both happen — flag it if it does, rather than
        # silently picking one.
        if igst > 0 and (cgst > 0 or sgst > 0):
            report.gstin_state_mismatches.append({
                "VOUCHERNUMBER": voucher_no,
                "GSTRATE": rate,
                "issue": "both IGST and CGST/SGST populated on the same rate bucket",
            })

        if taxable:
            r = dict(base)
            r["Ledger Name"] = sales_ledger_name(rate, interstate)
            r["Ledger Amount"] = round(taxable, 2)
            r["Ledger Amount Dr/Cr"] = "Cr"
            rows.append(r)
            total_cr += taxable

        if interstate:
            if igst:
                r = dict(base)
                r["Ledger Name"] = tax_ledger_name("IGST", rate)
                r["Ledger Amount"] = round(igst, 2)
                r["Ledger Amount Dr/Cr"] = "Cr"
                rows.append(r)
                total_cr += igst
        else:
            if cgst:
                r = dict(base)
                r["Ledger Name"] = tax_ledger_name("CGST", rate)
                r["Ledger Amount"] = round(cgst, 2)
                r["Ledger Amount Dr/Cr"] = "Cr"
                rows.append(r)
                total_cr += cgst
            if sgst:
                component = "UTGST" if config.home_state_is_ut else "SGST"
                r = dict(base)
                r["Ledger Name"] = tax_ledger_name(component, rate)
                r["Ledger Amount"] = round(sgst, 2)
                r["Ledger Amount Dr/Cr"] = "Cr"
                rows.append(r)
                total_cr += sgst

        # CESS, if the source data ever carries it (not present in either
        # sample — no per-unit/per-% breakdown available, so posted as a
        # flat named ledger rather than a "Output CESS x%" rate name).
        if cess:
            r = dict(base)
            r["Ledger Name"] = "Output CESS"
            r["Ledger Amount"] = round(cess, 2)
            r["Ledger Amount Dr/Cr"] = "Cr"
            rows.append(r)
            total_cr += cess

    # 3. Round Off — derived as the actual residual needed to balance to
    # BILLAMOUNT (bill_amount - total_cr), NOT copied from
    # invoice["ROUNDOFFAMOUNT"] directly. Layer 1 validates invoices within
    # a ₹1 tolerance, so a "validated" invoice's own ROUNDOFFAMOUNT field
    # could still leave a few paise unaccounted for; computing the residual
    # here guarantees this voucher balances exactly regardless. If the
    # residual and the invoice's stated ROUNDOFFAMOUNT disagree by more
    # than a token amount, that's worth a look — flagged separately below.
    residual = bill_amount - total_cr
    reported_round_off = float(invoice.get("ROUNDOFFAMOUNT") or 0.0)
    if abs(residual - reported_round_off) > 1.0:
        report.gstin_state_mismatches.append({
            "VOUCHERNUMBER": voucher_no,
            "issue": (f"computed round-off residual ({residual:.2f}) differs from "
                      f"invoice's own ROUNDOFFAMOUNT ({reported_round_off:.2f}) by more "
                      f"than Re. 1 — tax_breakup may not fully cover the bill amount"),
        })

    if abs(residual) > 0.004:
        r = dict(base)
        r["Ledger Name"] = config.round_off_ledger_name
        r["Ledger Amount"] = round(abs(residual), 2)
        r["Ledger Amount Dr/Cr"] = "Dr" if residual < 0 else "Cr"
        rows.append(r)

    # 4. Final balance check (check #3 from the brief) — recomputed cleanly
    # from the actual rows, not from running totals, so it can never drift.
    dr_total = sum(r["Ledger Amount"] for r in rows if r["Ledger Amount Dr/Cr"] == "Dr")
    cr_total = sum(r["Ledger Amount"] for r in rows if r["Ledger Amount Dr/Cr"] == "Cr")
    if abs(dr_total - cr_total) > config.balance_tolerance:
        report.balance_mismatches.append({
            "VOUCHERNUMBER": voucher_no,
            "dr_total": round(dr_total, 2),
            "cr_total": round(cr_total, 2),
            "difference": round(abs(dr_total - cr_total), 2),
        })

    report.vouchers_written += 1
    report.rows_written += len(rows)
    return rows


# ---------------------------------------------------------------------------
# Top-level entry point
# ---------------------------------------------------------------------------

def generate_tally_sales_export(invoices: list, config: TallyExportConfig = None):
    """Returns dict:
      {
        "B2B": (DataFrame, TallyExportReport),
        "B2C": (DataFrame, TallyExportReport),
      }
    """
    config = config or TallyExportConfig()
    b2b_invoices, b2c_invoices = split_b2b_b2c(invoices)

    results = {}
    for mode, inv_list, columns in (
        ("B2B", b2b_invoices, B2B_COLUMNS),
        ("B2C", b2c_invoices, B2C_COLUMNS),
    ):
        report = TallyExportReport(voucher_type="Sales", mode=mode, total_invoices_in=len(inv_list))
        all_rows = []
        for inv in inv_list:
            all_rows.extend(build_voucher_rows(inv, mode, config, report))
        df = pd.DataFrame(all_rows, columns=columns) if all_rows else pd.DataFrame(columns=columns)
        results[mode] = (df, report)

    return results


# ---------------------------------------------------------------------------
# NOTE for the Purchase pass (next step, not implemented yet):
# - Party ledger row becomes Cr (supplier), sales/tax ledgers become Dr
#   ("Local Purchase GST x%" / "Input CGST/SGST/UTGST/IGST x%" — naming to
#   be confirmed the same way as sales, no sample Purchase Tally template
#   provided yet).
# - Everything else (rate-bucket iteration, round-off sizing, balance
#   check, B2B/B2C split by GSTIN) carries over unchanged.
# ---------------------------------------------------------------------------
